name: maket
description: A Shopping Lists Manager.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  get_it: ^7.1.3
  provider: ^5.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  archive: ^3.0.0
  image: ^3.0.2
#  crypto: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/images/