const { BASE_ENDPOINT } = require("../../utils/constants/common");

module.exports = Object.freeze({
  USER_ENDPOINT: BASE_ENDPOINT + "user/",
  USER_REGISTER_ENDPOINT: "/",
  USER_LOGIN_ENDPOINT: "/me",
  USER_VERIFY_EMAIL_ENDPOINT: "/verify_email",
  USER_VERIFY_OTP_CODE_ENDPOINT: "/verify_otp_code",
  USER_UPDATE_PASSWORD_ENDPOINT: "/update_password",
  USER_NAME_MIN_LENGTH: 3,
  USER_NAME_MAX_LENGTH: 255,
  USER_EMAIL_MIN_LENGTH: 5,
  USER_EMAIL_MAX_LENGTH: 255,
  USER_PASSWORD_MIN_LENGTH: 8,
  USER_PASSWORD_MAX_LENGTH: 50,
  USER_HASHED_PASSWORD_MAX_LENGTH: 1024,
});
